### Study session 7 - Numpy and pandas series
#### BIOINF 575 - Fall 2021

#### SOLUTION

##### RECAP

#### Arrays of different dimensions (`shape` gives the number of elements on each dimension):

<img src="https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png" alt="data structures" width="500">  

_____


#### <b>Basic array attributes:</b>
* shape: array dimension
* size: Number of elements in array
* ndim: Number of array dimension (len(arr.shape))
* dtype: Data-type of the array
* slicing: [row_slice,col_slice]

Pandas Series a named array: 
```
pd.Series(data, index)
```

_____

<b><font color = "red">Exercise</font> <br></b>

Create a numpy 2D array of numbers from 1 to 3000 with 300 rows and 10 columns.   
Compute the mean of each row and count how many rows have a mean > 2000.

In [1]:
# Write your solution here



In [2]:
# import the numpy library to have access to the functionality that it provides

import numpy as np


In [3]:
# Create a numpy 2D array of numbers from 1 to 3000 with 300 rows and 10 columns.

# Because we are looking for a range of numbers we will use: 
# np.arange(start,stop) - start included, stop not included, so we add 1 to the value we really want to stop at
# it creates a 1-dimesional array 

np.arange(1, 3001)


array([   1,    2,    3, ..., 2998, 2999, 3000])

In [4]:
# Create a numpy 2D array of numbers from 1 to 3000 with 300 rows and 10 columns.

# we want a 2-dimensional array
# we reshape(nrows,ncols) the array to provide the right shape and dimensions
# the result of the arange method is an array so we can apply the reshape method to it

np.arange(1, 3001).reshape(300,10)


array([[   1,    2,    3, ...,    8,    9,   10],
       [  11,   12,   13, ...,   18,   19,   20],
       [  21,   22,   23, ...,   28,   29,   30],
       ...,
       [2971, 2972, 2973, ..., 2978, 2979, 2980],
       [2981, 2982, 2983, ..., 2988, 2989, 2990],
       [2991, 2992, 2993, ..., 2998, 2999, 3000]])

In [5]:
# Compute the mean of each row and count how many rows have a mean > 2000.

In [6]:
# we use the mean method to compute the mean
# the result of the reshape method is an array so we can apply the mean method to it
# with no parameters it computes the overall mean of the elements in the matrix

np.arange(1, 3001).reshape(300,10).mean()


1500.5

In [7]:
# check the type of an array

type(np.arange(1, 3001))


numpy.ndarray

In [8]:
# using the help on method mean allows us to see what arguments we can provide

help(np.ndarray.mean)


Help on method_descriptor:

mean(...)
    a.mean(axis=None, dtype=None, out=None, keepdims=False, *, where=True)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [9]:
# the axis argument allows us to apply the function on a specific dimension
# it is like a stack the last axis is always on top 
# 0 - columns
# 1 - rows

# back to our computation of the row means for our 2D array
# we will have 300 means - one for each row

np.arange(1, 3001).reshape(300,10).mean(1)


array([   5.5,   15.5,   25.5,   35.5,   45.5,   55.5,   65.5,   75.5,
         85.5,   95.5,  105.5,  115.5,  125.5,  135.5,  145.5,  155.5,
        165.5,  175.5,  185.5,  195.5,  205.5,  215.5,  225.5,  235.5,
        245.5,  255.5,  265.5,  275.5,  285.5,  295.5,  305.5,  315.5,
        325.5,  335.5,  345.5,  355.5,  365.5,  375.5,  385.5,  395.5,
        405.5,  415.5,  425.5,  435.5,  445.5,  455.5,  465.5,  475.5,
        485.5,  495.5,  505.5,  515.5,  525.5,  535.5,  545.5,  555.5,
        565.5,  575.5,  585.5,  595.5,  605.5,  615.5,  625.5,  635.5,
        645.5,  655.5,  665.5,  675.5,  685.5,  695.5,  705.5,  715.5,
        725.5,  735.5,  745.5,  755.5,  765.5,  775.5,  785.5,  795.5,
        805.5,  815.5,  825.5,  835.5,  845.5,  855.5,  865.5,  875.5,
        885.5,  895.5,  905.5,  915.5,  925.5,  935.5,  945.5,  955.5,
        965.5,  975.5,  985.5,  995.5, 1005.5, 1015.5, 1025.5, 1035.5,
       1045.5, 1055.5, 1065.5, 1075.5, 1085.5, 1095.5, 1105.5, 1115.5,
      

In [10]:
# check which means are > 2000
# the comparison operators are applied to each element of the array
# the result is a bool/logical array of size 300

np.arange(1, 3001).reshape(300,10).mean(1) > 2000


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [11]:
# bool is a subtype of int so logical values can be used to do numerical calculations 
# False will be 0 and True will be 1
# so we can call the sum method for the logical array
# adding up all the value in the logical array will tell us 
# for how many of the elements the condition is True
# because it adds 1 for each True and a 0 for each False

(np.arange(1, 3001).reshape(300,10).mean(1) > 2000).sum()


100

In [12]:
# we can also use the th built in function:

sum(np.arange(1, 3001).reshape(300,10).mean(1) > 2000)


100

In [13]:
# a solution with each step well separated:

num_vec = np.arange(1, 3001)
num_2D_vec = num_vec.reshape(300,10)
row_avg = num_2D_vec.mean(1)
logical_vec = row_avg > 2000
logical_vec.sum()


100

In [14]:
# number of dimensions

print(num_vec.ndim)
print(num_2D_vec.ndim)


1
2


In [15]:
# size of the array - total number of elements

print(num_vec.size)
print(num_2D_vec.size)


3000
3000


In [16]:
# shape of the array - number of elements on each dimension

print(num_vec.shape)
print(num_2D_vec.shape)


(3000,)
(300, 10)


In [17]:
# the builtin sum also works to add numerical/logical values in sequence types

print(sum([1, 2, 3, 4]))
print(sum([True, False, True]))
print(sum((True, 3, 4)))
print(sum({4, False}))
print(sum({1:"one", 2:"two"})) # for a dictionary it goes through the keys just like a for loop would

10
2
8
4
3


In [18]:
# the axis stack - 0 on top
# 3D array
x = np.array([[[1,2],[3,4],[5,6]],
             [[10,20],[30,40],[50,60]],
             [[100,200],[300,400],[500,600]],
             [[1000,2000],[3000,4000],[5000,6000]]])
x

array([[[   1,    2],
        [   3,    4],
        [   5,    6]],

       [[  10,   20],
        [  30,   40],
        [  50,   60]],

       [[ 100,  200],
        [ 300,  400],
        [ 500,  600]],

       [[1000, 2000],
        [3000, 4000],
        [5000, 6000]]])

In [19]:
x.shape

(4, 3, 2)

In [20]:
# The first dimension, the one with the number of rows dissapeared, the one that had four elements
# The average is made over the number of rows

x.mean(0)  


array([[ 277.75,  555.5 ],
       [ 833.25, 1111.  ],
       [1388.75, 1666.5 ]])

In [21]:
[1111/4, 2222/4]

[277.75, 555.5]

In [22]:
# The second dimension from the nested list, the one that had three elements, dissapeared
# The average is made over the number of elements in the second dimension (number of columns)

x.mean(1) # The dimension in the middle, the one with three elements, dissapeared

array([[3.e+00, 4.e+00],
       [3.e+01, 4.e+01],
       [3.e+02, 4.e+02],
       [3.e+03, 4.e+03]])

In [23]:
# The deepest dimension from the nested list, the one that had two elements, dissapeared
# The average is made over the number of elements in the third dimension

x.mean(2) 


array([[1.5e+00, 3.5e+00, 5.5e+00],
       [1.5e+01, 3.5e+01, 5.5e+01],
       [1.5e+02, 3.5e+02, 5.5e+02],
       [1.5e+03, 3.5e+03, 5.5e+03]])

___

<b> <font color = "red">Exercise</font></b>

Break the series in two groups based on the following labels and compute the mean of the rows for each group:
```python
labels = ["Group1", "Group1", "Group2", "Group2", "Group1",
          "Group2", "Group2", "Group1", "Group1", "Group1"]
```

Compute the difference between the means of the two groups (Group 1 mean - Group 2 mean)

Create a pandas series from the result of the difference, using the labels: "Row1", ... "Row300"

Select the rows with a difference between  and 3 and 3.5

In [24]:
# Write your solution here



In [25]:
# 2D vector
num_2D_vec

array([[   1,    2,    3, ...,    8,    9,   10],
       [  11,   12,   13, ...,   18,   19,   20],
       [  21,   22,   23, ...,   28,   29,   30],
       ...,
       [2971, 2972, 2973, ..., 2978, 2979, 2980],
       [2981, 2982, 2983, ..., 2988, 2989, 2990],
       [2991, 2992, 2993, ..., 2998, 2999, 3000]])

In [26]:
# these are column labels: 10 columns 10 labels

labels = ["Group1", "Group1", "Group2", "Group2", "Group1",
          "Group2", "Group2", "Group1", "Group1", "Group1"]

In [27]:
# checks if the list is equal to the string and it is not

labels == "Group1"


False

In [28]:
# if we create an array we can check each element

labels_vec = np.array(labels)
labels_vec


array(['Group1', 'Group1', 'Group2', 'Group2', 'Group1', 'Group2',
       'Group2', 'Group1', 'Group1', 'Group1'], dtype='<U6')

In [29]:
# the result of checking a condition on an array is a logical array of the same dim

labels_vec == "Group1"


array([ True,  True, False, False,  True, False, False,  True,  True,
        True])

In [30]:
# we can use this condition to do conditional subsetting [cond_sel_rows, cond_sel_cols]
# the cond_sel_row will be a logical array that has the size equal to the number of rows
# the cond_sel_cols will be a logical array that has the size equal to the number of columns

# get all rows, :, and the columns for only group 1

data_group1 = num_2D_vec[:, labels_vec == "Group1"]
data_group1


array([[   1,    2,    5,    8,    9,   10],
       [  11,   12,   15,   18,   19,   20],
       [  21,   22,   25,   28,   29,   30],
       ...,
       [2971, 2972, 2975, 2978, 2979, 2980],
       [2981, 2982, 2985, 2988, 2989, 2990],
       [2991, 2992, 2995, 2998, 2999, 3000]])

In [31]:
# get all rows, :, and the columns for only group 2

data_group2 = num_2D_vec[:, labels_vec == "Group2"]
data_group2


array([[   3,    4,    6,    7],
       [  13,   14,   16,   17],
       [  23,   24,   26,   27],
       ...,
       [2973, 2974, 2976, 2977],
       [2983, 2984, 2986, 2987],
       [2993, 2994, 2996, 2997]])

In [32]:
# Compute the difference between the means of the two groups (Group 1 mean - Group 2 mean)

# we compute the mean for the rows for group1 data and group2 data 
# and compute the difference which because the they have the same size (number of rows = 300)
# will be done element with respective element based on position on the array

diff_means = data_group1.mean(1) - data_group2.mean(1)
diff_means
# The results all all the same because of the way the data is created all columns differ by a constant 

array([0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333333,
       0.83333333, 0.83333333, 0.83333333, 0.83333333, 0.83333

In [33]:
# create labels for rows - use a for loop

row_labels = []
for i in range(1,301):
    lbl = f"Row{i}"
    row_labels.append(lbl)
print(row_labels)

['Row1', 'Row2', 'Row3', 'Row4', 'Row5', 'Row6', 'Row7', 'Row8', 'Row9', 'Row10', 'Row11', 'Row12', 'Row13', 'Row14', 'Row15', 'Row16', 'Row17', 'Row18', 'Row19', 'Row20', 'Row21', 'Row22', 'Row23', 'Row24', 'Row25', 'Row26', 'Row27', 'Row28', 'Row29', 'Row30', 'Row31', 'Row32', 'Row33', 'Row34', 'Row35', 'Row36', 'Row37', 'Row38', 'Row39', 'Row40', 'Row41', 'Row42', 'Row43', 'Row44', 'Row45', 'Row46', 'Row47', 'Row48', 'Row49', 'Row50', 'Row51', 'Row52', 'Row53', 'Row54', 'Row55', 'Row56', 'Row57', 'Row58', 'Row59', 'Row60', 'Row61', 'Row62', 'Row63', 'Row64', 'Row65', 'Row66', 'Row67', 'Row68', 'Row69', 'Row70', 'Row71', 'Row72', 'Row73', 'Row74', 'Row75', 'Row76', 'Row77', 'Row78', 'Row79', 'Row80', 'Row81', 'Row82', 'Row83', 'Row84', 'Row85', 'Row86', 'Row87', 'Row88', 'Row89', 'Row90', 'Row91', 'Row92', 'Row93', 'Row94', 'Row95', 'Row96', 'Row97', 'Row98', 'Row99', 'Row100', 'Row101', 'Row102', 'Row103', 'Row104', 'Row105', 'Row106', 'Row107', 'Row108', 'Row109', 'Row110', 'Row111

In [34]:
# Create a pandas array - make pandas library functionality available using import
# good practice recommends to put all import statments at the beginning of the notebook

import pandas as pd


In [35]:
# Create a pandas series from the result of the difference, using the labels: "Row1", ... "Row300"

# use the function pd.Series - pandas uses the capitalized name
# the data and the index should be compatible - same size

named_diff = pd.Series(data = diff_means, index = row_labels)
named_diff

Row1      0.833333
Row2      0.833333
Row3      0.833333
Row4      0.833333
Row5      0.833333
            ...   
Row296    0.833333
Row297    0.833333
Row298    0.833333
Row299    0.833333
Row300    0.833333
Length: 300, dtype: float64

In [36]:
# count the frequencies of the values in the array

named_diff.value_counts()


0.833333    103
0.833333     95
0.833333     51
0.833333     25
0.833333     13
0.833333      7
0.833333      3
0.833333      1
0.833333      1
0.833333      1
dtype: int64

In [37]:
# Select the rows with a difference between and 3 and 3.5

named_diff[(named_diff > 3) & (named_diff < 3.5)] 

# results in an empty series because none of the elements meet the condition 
# since they are all around 8.3


Series([], dtype: float64)

In [38]:
# create a named array (pd.Series) of 5 values

x = pd.Series(range(5), index = ["gene1", "gene2", "gene3", "gene4", "gene5"])
x


gene1    0
gene2    1
gene3    2
gene4    3
gene5    4
dtype: int64

In [39]:
# get the genes with values > 1 AND <=  3

x[(x > 1)  & (x <= 3)]


gene3    2
gene4    3
dtype: int64

In [40]:
# get the genes with values < 2 OR >  3

x[(x < 2) | (x > 3)]


gene1    0
gene2    1
gene5    4
dtype: int64

In [41]:
# array of 300 x 10

num_2D_vec


array([[   1,    2,    3, ...,    8,    9,   10],
       [  11,   12,   13, ...,   18,   19,   20],
       [  21,   22,   23, ...,   28,   29,   30],
       ...,
       [2971, 2972, 2973, ..., 2978, 2979, 2980],
       [2981, 2982, 2983, ..., 2988, 2989, 2990],
       [2991, 2992, 2993, ..., 2998, 2999, 3000]])

In [42]:
# the result of checking a condition on an array is a logical array of the same dim

num_2D_vec > 200


array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

___
<b><font color = "red">Exercise</font> <br><br></b>

Explain the following code:



In [43]:
def downstream_overlap(gene1, gene2, network):
    downstream_gene1 = network.get(gene1, set())
    downstream_gene2 = network.get(gene2, set())
    n = len(downstream_gene1.union(downstream_gene2))
    m = len(downstream_gene1.intersection(downstream_gene2))
    overlap = 0
    if n > 0: 
        overlap = 100*m/n
    return overlap

In [44]:
test_network = {
    "Gene1": {"Gene2"},
    "Gene3": {"Gene1", "Gene4", "Gene5"},
    "Gene4": {"Gene1", "Gene2", "Gene5", "Gene6"},
    "Gene5": {"Gene2", "Gene3", "Gene4"}
}
downstream_overlap("Gene3","Gene4", test_network)

40.0

In [45]:
## Write your code description here

## This is a much more elaborate description than what I expect for the homework.

print(
"""
The code in the second cell creates a dictionary with 
genes as keys and gene sets as values.
I assume the dictionary holds the regulatory relations between genes where 
the key gene regulates the expression of the genes in the value set. 
Then, the function downstream_overlap is called with three arguments, 
two gene symbols and the dictionary.

Overall the function downstream_overlap computes the percentage of overlap 
between the union and the intersection of the sets ofgenes they regulate.
The function downstream_overlap takes as arguments gene1, gene2, and network.
The arguments/parameters gene1, and gene2 are gene symbols of the genes we
want to compute the overalp for.
The argument network is a dictionary with the regulatory relations between genes,
where the key gene regulates the expression of the genes in the value set.
The first statement takes from the network dictionary (.get) the value for the key 
given by the gene symbol in gene1 and assigns it to the variable downstream_gene1.
If the gene1 symbol is not a key then an empty set (set()) is retrieved by the get method.
The second statement takes from the network dictionary the value for the key 
given by the gene symbol in gene2 and assigns it to the variable downstream_gene2.
If the gene2 symbol is not a key then an empty set (set()) is retrieved by the get method.
The third statement computes the length (len) of the union between the set in downstream_gene1 
and the set in downstream_gene2 and assigns it to the variable n. 
The variable n gets assigned the number of genes regulated by either gene1 or gene2.
The fourth statement computes the length (len) of the intersection between the set in 
downstream_gene1 and the set in downstream_gene2 and assigns it to the variable m. 
The variable m gets assigned the number of genes regulated by both gene1 and gene2.
The variable overlap gets assigned the value 0.
If the size of the union is greater then 0, between the two of them gene1 and gene2 
regulate the expression of at least one gene, the overlap variable gets assigned   
the ratio between m and n and multiplid by 100.
Meaning the overap becomes the percentage the intersection of the two sets is 
when looking at the union of the two sets.
If the sets coincide the union and intersection have the same size m=n (m/n =1) 
and the overlap is 100*1.
At the end the value in the overalp variable is returned.
Intially the overlap is assumed to be 0 then, if the sets we are computing 
the overlap are not empty (n > 0) we compute the overlap.
The formula involves division by n so it should be > 0 to avoid division by 0.

For Gene3 and Gene4 the overlap is 40 (40%)
union: {"Gene1", "Gene2", "Gene4" "Gene5", "Gene6"} => n = 5
intersection: {"Gene1", "Gene5"} => m = 2
100*2/5 = 40
"""
)


The code in the second cell creates a dictionary with 
genes as keys and gene sets as values.
I assume the dictionary holds the regulatory relations between genes where 
the key gene regulates the expression of the genes in the value set. 
Then, the function downstream_overlap is called with three arguments, 
two gene symbols and the dictionary.

Overall the function downstream_overlap computes the percentage of overlap 
between the union and the intersection of the sets ofgenes they regulate.
The function downstream_overlap takes as arguments gene1, gene2, and network.
The arguments/parameters gene1, and gene2 are gene symbols of the genes we
want to compute the overalp for.
The argument network is a dictionary with the regulatory relations between genes,
where the key gene regulates the expression of the genes in the value set.
The first statement takes from the network dictionary (.get) the value for the key 
given by the gene symbol in gene1 and assigns it to the variable downstre